const sampleProjects = [
    {
      id: 1,
      title: 'Proyecto 1',
      description: 'Este es un proyecto de ejemplo número 1.',
      imageUrl: '/images/project1.jpg',
      url: 'https://ejemplo.com/proyecto1',
      technologies: ['React', 'Node.js'],
      date: 'Enero 2022',
      client: 'Cliente A',
    },
    {
      id: 2,
      title: 'Proyecto 2',
      description: 'Este es un proyecto de ejemplo número 2.',
      imageUrl: '/images/project2.jpg',
      url: 'https://ejemplo.com/proyecto2',
      technologies: ['Angular', 'Python'],
      date: 'Febrero 2022',
      client: 'Cliente B',
    },
    {
      id: 3,
      title: 'Proyecto 3',
      description: 'Este es un proyecto de ejemplo número 3.',
      imageUrl: '/images/project3.jpg',
      url: 'https://ejemplo.com/proyecto3',
      technologies: ['Vue.js', 'Ruby'],
      date: 'Marzo 2022',
      client: 'Cliente C',
    },
    {
      id: 4,
      title: 'Proyecto 4',
      description: 'Este es un proyecto de ejemplo número 4.',
      imageUrl: '/images/project4.jpg',
      url: 'https://ejemplo.com/proyecto4',
      technologies: ['React', 'Node.js'],
      date: 'Abril 2022',
      client: 'Cliente D',
    },
    {
      id: 5,
      title: 'Proyecto 5',
      description: 'Este es un proyecto de ejemplo número 5.',
      imageUrl: '/images/project5.jpg',
      url: 'https://ejemplo.com/proyecto5',
      technologies: ['Angular', 'Python'],
      date: 'Mayo 2022',
      client: 'Cliente E',
    },
    {
      id: 6,
      title: 'Proyecto 6',
      description: 'Este es un proyecto de ejemplo número 6.',
      imageUrl: '/images/project6.jpg',
      url: 'https://ejemplo.com/proyecto6',
      technologies: ['Vue.js', 'Ruby'],
      date: 'Junio 2022',
      client: 'Cliente F',
    },
    {
      id: 7,
      title: 'Proyecto 7',
      description: 'Este es un proyecto de ejemplo número 7.',
      imageUrl: '/images/project7.jpg',
      url: 'https://ejemplo.com/proyecto7',
      technologies: ['React', 'Node.js'],
      date: 'Julio 2022',
      client: 'Cliente G',
    },
    {
      id: 8,
      title: 'Proyecto 8',
      description: 'Este es un proyecto de ejemplo número 8.',
      imageUrl: '/images/project8.jpg',
      url: 'https://ejemplo.com/proyecto8',
      technologies: ['Angular', 'Python'],
      date: 'Agosto 2022',
      client: 'Cliente H',
    },
    {
      id: 9,
      title: 'Proyecto 9',
      description: 'Este es un proyecto de ejemplo número 9.',
      imageUrl: '/images/project9.jpg',
      url: 'https://ejemplo.com/proyecto9',
      technologies: ['Vue.js', 'Ruby'],
      date: 'Septiembre 2022',
      client: 'Cliente I',
    },
    {
      id: 10,
      title: 'Proyecto 10',
      description: 'Este es un proyecto de ejemplo número 10.',
      imageUrl: '/images/project10.jpg',
      url: 'https://ejemplo.com/proyecto10',
      technologies: ['React', 'Node.js'],
      date: 'Octubre 2022',
      client: 'Cliente J',
    },
  ]
  
  export default sampleProjects
  